[build]
  base = "speedtest-app/"
  command = "npm run build"
  publish = "out"  # Next.js static export goes to 'out' directory

# These redirects are crucial for Next.js apps on Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"