[build]
  base = "speedtest-app/"
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "22.0.0"  # Updated to Node.js 22
  NPM_FLAGS = "--no-optional"
  NETLIFY_USE_PNPM = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_FORCE_MUSL_LIBC = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"