[build]
  base = "speedtest-app/"
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-optional"
  NETLIFY_USE_PNPM = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  # Force the use of the musl variant
  NEXT_FORCE_MUSL_LIBC = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"